# This is a basic workflow to help you get started with Actions

name: Dev CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_email: ${{ secrets.DEV_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.DEV_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.DEV_PROJECT_ID }}
          export_default_credentials: false
      - name: Deploy the function
        run: gcloud functions deploy docs-builder
